Forms
Dadadon/blog pull request #12
Opened 2023-04-15 18:04 UTC by Dadadon

- Created a method called current_user in your ApplicationController to make current user data available to all controllers.
> It will return the first user from the database.

**Created** forms to perform the following functions:
- Creates a Post on behalf of the current_user (used the method that was created in the ApplicationController).
- Created a comment on behalf of the current_user (used the method that was created in theApplicationController).
- Allow Users to add likes to Posts.

2023-04-15 18:50 UTC, franclobo requested changes
Hi, @Dadadon,

# Required Changes ♻️

![so-close-jim-halpert](https://user-images.githubusercontent.com/58642949/232248039-fa41c522-7e83-49fa-ab48-6ff5d509ef8e.gif)

Good job so far!
You are doing it well 👏🏽 there are some issues that you still need to work on to go to the next project but you are 

## Highlights

- No linter errors ✔️ 
- Correct Git flow ✔️ 
- Descriptive PR ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] Before defining the create method we need to define the new method in the comments controller file, the build method is not defined 👇🏽 

![image](https://user-images.githubusercontent.com/58642949/232246895-de48fe56-a391-4e22-9842-d78345893f3e.png)

- [ ] Please create the routes for comments and likes to be able to create comments and give likes.

![image](https://user-images.githubusercontent.com/58642949/232247976-d5a81f80-d94b-4823-862f-3a1d6842ee10.png)

- [ ] I couldn't find the forms to create a new post or comments, please 🙏🏽 complete all the project requirements to move to the next milestone.


> Create forms to perform the following functions:
> Creates a Post on behalf of the current_user (use the method that you created in your ApplicationController).
> Create a comment on behalf of the current_user (use the method that you created in your ApplicationController).
> Allow Users to add likes to Posts.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-15 18:50 UTC, franclobo commented on app/controllers/posts_controller.rb
> +    @like = @post.likes.build(user: current_user)
- [ ] The method build is not defined, please 🙏🏽 correct the create method with: 👇🏽 

`@post = @current_user.posts.new(post_params)`

2023-04-15 19:52 UTC, anagudelogu requested changes
# STATUS: CHANGES REQUIRED ♻️ 🚧 

Hi @Dadadon 👋🏼 
I'm Andres.

You've done a great job implementing some of the requested changes for this milestone 🚀, but there are still some which haven't been addressed yet. You're getting closer, keep up the good work! 🤖 🎆 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

 ## Highlights
✅ Great use of GitHub flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Great UI design. 💻 
✅ Descriptive PR title, summary and commit messages. 💬 


 ## Required Changes ♻️
_Check the comments under the review._

- [ ] As suggested by the previous reviewer, please consider adding the routes to create likes and comments, at the moment they aren't present, so these features aren't working. 🤓 🔧 

![image](https://user-images.githubusercontent.com/77069011/232250462-00144e72-826b-475b-b02d-e0ed6e23f375.png)

- [ ] Also, navigating to the new post route throws the following error:

![image](https://user-images.githubusercontent.com/77069011/232250504-a9de631c-9b4a-4158-9d18-3fd1392692c1.png)

Thus I'm not able to review your form UI, perhaps the same happened to the previous reviewer as he wasn't able to find any of the forms:
>I couldn't find the forms to create a new post or comments, please 🙏🏽 complete all the project requirements to move to the next milestone. 

Please consider fixing this error! 🤓 🔧 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-15 21:41 UTC, vickymarz approved these changes
Hi @Dadadon, 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
congratulations!  🎉💯🌟 

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Required changes done ✅ 

<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-15 21:58 UTC, merged

2023-06-22 15:37 UTC, franclobo reviewed
Hi @Dadadon, 

# STATUS: APPROVED 😃 

![git-merge](https://github.com/Dadadon/blog/assets/58642949/f268418d-86dd-44b8-b1d5-e76dcef3d60e)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- No linter errors ✔️ 
- Descriptive PR ✔️ 
- Correct Git flow ✔️ 
- Good UI ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._