Controller spec
Dadadon/blog pull request #15
Opened 2023-06-15 14:27 UTC by Dadadon

**
> Added RSpec as a gem to the project.
**
Created a Request spec file for controllers.
**
> For each action I checked:
**

- If the response status was correct.
- If a correct template was rendered.
- If the response body includes the correct placeholder text.

2023-06-15 14:55 UTC, GzimAsani requested changes
### Hello, @Dadadon                    :wave:   
 Good job so far,  done There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ## Highlights
 * Good job adding all the necessary tests +1: 

 ## Required Changes 

- [ ] Check for the comments below :arrow_double_down: 

 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- N/A



Cheers and Happy coding! clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-15 14:55 UTC, GzimAsani commented on README.md
> +
- [ ] I can see that you added all the necessary tests and they should pass, but unfortunately you have some problems with gemfile and gems therefore I am unable to run rspec, kindly fix it:
![image](https://github.com/Dadadon/blog/assets/62705947/7afb5a4d-f434-42d5-a70e-ad835e9853b0)
![image](https://github.com/Dadadon/blog/assets/62705947/a6752f0a-0d89-46dc-89e9-d4b4669434b8)

2023-06-15 21:36 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle: 

Hi @Dadadon, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-15 21:36 UTC, Qoosim commented on spec/views/post_index_spec.rb
> +end
- [ ] Great work so far. However, there're few things to do before your project could be approved. According to the project requirements, you're expect to write test that ensures correct view template is rendered for both the index and show for the post controller.


```
 expect(response).to render_template(:index)

```

- [ ] Your test cases should include a test  that ensures the response body for the correct placeholder text. 

```
   Example :
      expect(response.body).to include("Welcome to post index page")

```

### Project Requirements

![test](https://github.com/Dadadon/blog/assets/26597432/3ace53a6-4fb8-4a5a-81cf-d1a0063995a7)

2023-06-15 21:36 UTC, Qoosim commented on spec/views/post_show_spec.rb
> +end
- [ ] According to the project requirements, you're expect to write test that ensures correct view template is rendered for both the index and show for the post controller.


```
 expect(response).to render_template(:show)

```

- [ ] Your test cases should include a test  that ensures the response body for the correct placeholder text. 

```
Example :
expect(response.body).to include("Welcome to post show  page")

```

### Project Requirements

![test](https://github.com/Dadadon/blog/assets/26597432/3ace53a6-4fb8-4a5a-81cf-d1a0063995a7)

2023-06-15 21:36 UTC, Qoosim commented on spec/views/user_index_spec.rb
> +end
- [ ] According to the project requirements, you're expect to write test that ensures correct view template is rendered for both the index and show for the post controller.


```
expect(response).to render_template(:index)

```

- [ ] Your test cases should include a test  that ensures the response body for the correct placeholder text. 

```
Example :
   expect(response.body).to include("Welcome to user index  page")

```

### Project Requirements

![test](https://github.com/Dadadon/blog/assets/26597432/3ace53a6-4fb8-4a5a-81cf-d1a0063995a7)

2023-06-15 21:36 UTC, Qoosim commented on spec/views/user_show_spec.rb
> +end
- [ ] According to the project requirements, you're expect to write test that ensures correct view template is rendered for both the index and show for the post controller.


```
expect(response).to render_template(:show)

```

- [ ] Your test cases should include a test  that ensures the response body for the correct placeholder text. 

```
Example :
expect(response.body).to include("Welcome to user show  page")

```

### Project Requirements

![test](https://github.com/Dadadon/blog/assets/26597432/3ace53a6-4fb8-4a5a-81cf-d1a0063995a7)

2023-06-16 22:43 UTC, MahmoudBakr23 approved these changes
Hi @Dadadon 😃, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

**Highlights**
- Well done on adding the necessary integration tests for your controllers

Cheers, and Happy coding!👏👏👏

Feel free to mention @MahmoudBakr23 to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-16 22:47 UTC, merged

2023-06-20 16:22 UTC, DammyShittu reviewed
Hi @Dadadon,

## APPROVED 🟢

## Highlights
✔️ Passing tests

Great implementation of all the requirements in this milestone. 👏 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-22 14:21 UTC, joel-kalema reviewed
Hi @Dadadon 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# Congratulations! 🎉 

![ ](https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif)
## Highlights
Linters are passing 👍 
The project is running successfully 👍 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@joel-kalema** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._